server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

youtube:
  api:
    base-url: https://youtube.googleapis.com/youtube/v3/commentThreads
    key: ${YOUTUBE_API_KEY}

app:
  aiWorker:
    base-url: ${AI_WORKER_PATH:http://localhost:8082/api/aiworker}